# Generated by Django 3.2.8 on 2021-11-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='report_images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='report_images'),
        ),
    ]
