# Generated by Django 3.2.8 on 2021-11-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_auto_20211103_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_report',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdf_reports'),
        ),
        migrations.AddField(
            model_name='report',
            name='zip',
            field=models.FileField(blank=True, default=None, null=True, upload_to='encrypted_zip_files'),
        ),
        migrations.AlterField(
            model_name='report',
            name='img_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='report_images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='img_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='report_images'),
        ),
    ]
