# Generated by Django 3.2.8 on 2021-11-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_auto_20211110_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='files')),
            ],
        ),
    ]
