# Generated by Django 3.2.8 on 2021-11-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
